-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 16:07:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Land`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Land` (
  `Land_ISO` VARCHAR(2) NOT NULL,
  `Land` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Land_ISO`),
  UNIQUE INDEX `Land_ISO_UNIQUE` (`Land_ISO` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ort` (
  `OrtID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PLZ` VARCHAR(8) NOT NULL,
  `Ort` VARCHAR(30) NOT NULL,
  `Kanton` VARCHAR(2) NULL,
  `Land_Land_ISO` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`OrtID`, `Land_Land_ISO`),
  UNIQUE INDEX `OrtID_UNIQUE` (`OrtID` ASC),
  INDEX `fk_Ort_Land1_idx` (`Land_Land_ISO` ASC),
  CONSTRAINT `fk_Ort_Land1`
    FOREIGN KEY (`Land_Land_ISO`)
    REFERENCES `Land` (`Land_ISO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Marker` (
  `MarkerID` INT NOT NULL,
  `icon` VARCHAR(255) NULL,
  `color` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`MarkerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lernende`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lernende` (
  `LernendeID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(30) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Ort_OrtID` BIGINT(20) NOT NULL,
  `Marker_MarkerID` INT NOT NULL,
  PRIMARY KEY (`LernendeID`, `Ort_OrtID`, `Marker_MarkerID`),
  UNIQUE INDEX `LernendeID_UNIQUE` (`LernendeID` ASC),
  INDEX `fk_Lernende_Ort_idx` (`Ort_OrtID` ASC),
  INDEX `fk_Lernende_Marker1_idx` (`Marker_MarkerID` ASC),
  CONSTRAINT `fk_Lernende_Ort`
    FOREIGN KEY (`Ort_OrtID`)
    REFERENCES `Ort` (`OrtID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lernende_Marker1`
    FOREIGN KEY (`Marker_MarkerID`)
    REFERENCES `Marker` (`MarkerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
